server:
  port: 1102
  
spring:
  application:
    name: ac-sc-manager-provider
  datasource:
    name: mydb2
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/project01?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
      
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
      