server:
  port: 80
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
    register-with-eureka: false
    
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    
tracker:
  config:
    location: /tracker.conf

